package es.upm.fi.cig.mctbnc.learning.structure.optimization.hillclimbing.implementation;

import java.util.Map;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import es.upm.fi.cig.mctbnc.learning.structure.optimization.hillclimbing.HillClimbingSolution;
import es.upm.fi.cig.mctbnc.learning.structure.optimization.scores.bn.BNScoreFunction;
import es.upm.fi.cig.mctbnc.models.BN;
import es.upm.fi.cig.mctbnc.models.PGM;
import es.upm.fi.cig.mctbnc.nodes.Node;
import es.upm.fi.cig.mctbnc.util.Util;

/**
 * Implements hill climbing algorithm for BNs.
 * 
 * @author Carlos Villa Blanco
 *
 */
public class BNHillClimbing implements HillClimbingImplementation {
	BNScoreFunction scoreFunction;
	static Logger logger = LogManager.getLogger(BNHillClimbing.class);

	/**
	 * Constructor that receives the score function to optimize.
	 * 
	 * @param scoreFunction
	 */
	public BNHillClimbing(BNScoreFunction scoreFunction) {
		this.scoreFunction = scoreFunction;
	}

	@Override
	public HillClimbingSolution findStructure(PGM<? extends Node> pgm) {
		// Retrieve the model, initial structure and number of nodes
		BN<? extends Node> bn = (BN<? extends Node>) pgm;
		boolean[][] currentStructure = bn.getAdjacencyMatrix().clone();
		int numNodes = currentStructure.length;
		// Define object to store final solution
		HillClimbingSolution solution = new HillClimbingSolution();
		solution.setAdjacencyMatrix(currentStructure);
		solution.setScore(Double.NEGATIVE_INFINITY);
		boolean improvement;
		do {
			improvement = false;
			// Store scores and respective structures for each operation (addition, deletion
			// and reversal)
			double[] scores = { Double.NEGATIVE_INFINITY, Double.NEGATIVE_INFINITY, Double.NEGATIVE_INFINITY };
			boolean[][][] adjacencyMatrices = new boolean[3][numNodes][numNodes];
			// Structures generated by addition
			findBestNeighbor(bn, currentStructure, scores, adjacencyMatrices, "addition");
			// Structures generated by deletion
			findBestNeighbor(bn, currentStructure, scores, adjacencyMatrices, "deletion");
			// Structures generated by reversal
			findBestNeighbor(bn, currentStructure, scores, adjacencyMatrices, "reversal");
			int idxBestOperation = Util.getIndexLargestValue(scores);
			double iterationBestScore = scores[idxBestOperation];
			logger.trace("Iteration best score {}", iterationBestScore);
			if (iterationBestScore > solution.getScore()) {
				logger.debug("Score improved! From {} to {}", solution.getScore(), iterationBestScore);
				logger.debug("New structure: {}", (Object) adjacencyMatrices[idxBestOperation]);
				currentStructure = adjacencyMatrices[idxBestOperation];
				solution.setAdjacencyMatrix(adjacencyMatrices[idxBestOperation]);
				solution.setScore(iterationBestScore);
				improvement = true;
			}
		} while (improvement);
		return solution;
	}

	/**
	 * Find the best neighbor of the adjacency matrix "bestStructure" given an
	 * operation to perform.
	 * 
	 * @param bestStructure
	 * @param scores
	 * @param adjacencyMatrices
	 * @param cache
	 * @param operation         Possible operations to perform over the adjacency
	 *                          matrix. These are addition, deletion or reversal of
	 *                          arcs.
	 */
	private void findBestNeighbor(BN<? extends Node> bn, boolean[][] bestStructure, double[] scores,
			boolean[][][] adjacencyMatrices, String operation) {
		// Define the index of the operation. It will be used to store the score and
		// adjacency matrix
		// in the correct position of the arrays.
		int idxOperation = operation == "addition" ? 0 : operation == "deletion" ? 1 : 2;
		int numNodes = bestStructure.length;
		for (int i = 0; i < numNodes; i++) {
			for (int j = 0; j < numNodes; j++)
				if (i != j) {
					// Copy current best neighbor
					boolean[][] tempAdjacencyMatrix = new boolean[numNodes][numNodes];
					for (int r = 0; r < numNodes; r++)
						tempAdjacencyMatrix[r] = bestStructure[r].clone();
					if (operation == "addition") {
						if (tempAdjacencyMatrix[i][j])
							// If there is already an arc, the operation is not performed
							continue;
						// Arc is added
						tempAdjacencyMatrix[i][j] = true;
					} else if (operation == "deletion") {
						if (!tempAdjacencyMatrix[i][j])
							// If there is no arc, the operation cannot be performed
							continue;
						// Arc is removed
						tempAdjacencyMatrix[i][j] = false;
					} else {
						if (!tempAdjacencyMatrix[i][j])
							// If there is no arc, the operation cannot be performed
							continue;
						// Arc is reversed
						tempAdjacencyMatrix[i][j] = false;
						tempAdjacencyMatrix[j][i] = true;
					}
					if (bn.isStructureLegal(tempAdjacencyMatrix)) {
						logger.trace("Studying new {} structure: {}", bn.getType(), tempAdjacencyMatrix);
						// Retrieve score BN with the modified adjacency matrix
						double score = computeScore(bn, tempAdjacencyMatrix);
						if (scores[idxOperation] < score) {
							scores[idxOperation] = score;
							adjacencyMatrices[idxOperation] = tempAdjacencyMatrix;
						}
					}
				}
		}
	}

	/**
	 * Compute the score of a structure given an adjacency matrix.
	 * 
	 * @param indexNode
	 * @param adjacencyMatrix
	 * @return score
	 */
	private double computeScore(BN<? extends Node> bn, boolean[][] adjacencyMatrix) {
		// Establish the structure defined in an adjacency matrix and return its score
		bn.setStructureModifiedNodes(adjacencyMatrix);
		return this.scoreFunction.compute(bn);
	}

	@Override
	public Map<String, String> getInfoScoreFunction() {
		return Map.of("scoreFunction", scoreFunction.getIdentifier(), "penalizationFunction",
				scoreFunction.getPenalization());
	}

}
