package es.upm.fi.cig.multictbnc.learning.structure.optimisation.hillclimbing.implementation;

import es.upm.fi.cig.multictbnc.learning.structure.optimisation.hillclimbing.HillClimbingSolution;
import es.upm.fi.cig.multictbnc.learning.structure.optimisation.scores.ctbn.CTBNScoreFunction;
import es.upm.fi.cig.multictbnc.models.CTBN;
import es.upm.fi.cig.multictbnc.models.PGM;
import es.upm.fi.cig.multictbnc.nodes.Node;
import es.upm.fi.cig.multictbnc.util.Util;
import org.apache.commons.lang3.NotImplementedException;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.util.List;
import java.util.Map;

/**
 * Implements hill climbing algorithm for CTBNs. This class is used with scores that cannot be optimised by finding the
 * best parent set for each node individually. This is the case of, for example, the conditional log-likelihood.
 *
 * @author Carlos Villa Blanco
 */
public class CTBNHillClimbing implements HillClimbingImplementation {
	private static final Logger logger = LogManager.getLogger(CTBNHillClimbing.class);
	CTBNScoreFunction scoreFunction;

	/**
	 * Constructor that receives the score function to optimise.
	 *
	 * @param scoreFunction score function for continuous-time Bayesian networks
	 */
	public CTBNHillClimbing(CTBNScoreFunction scoreFunction) {
		this.scoreFunction = scoreFunction;
	}

	@Override
	public HillClimbingSolution findStructure(PGM<? extends Node> pgm) {
		logger.info("Learning {} using Hill Climbing", pgm.getType());
		// Retrieve the model, initial structure and number of nodes
		CTBN<? extends Node> ctbn = (CTBN<? extends Node>) pgm;
		boolean[][] currentStructure = pgm.getAdjacencyMatrix().clone();
		int numNodes = currentStructure.length;
		// Define object to store final solution
		HillClimbingSolution solution = new HillClimbingSolution();
		solution.setScore(Double.NEGATIVE_INFINITY);
		boolean improvement;
		do {
			improvement = false;
			// Store scores and respective structures for each operation (addition, deletion
			// and reversal)
			double[] scores = {Double.NEGATIVE_INFINITY, Double.NEGATIVE_INFINITY, Double.NEGATIVE_INFINITY};
			boolean[][][] adjacencyMatrices = new boolean[3][numNodes][numNodes];
			// Structures generated by addition
			findBestNeighbor(ctbn, currentStructure, scores, adjacencyMatrices, "addition");
			// Structures generated by deletion
			findBestNeighbor(ctbn, currentStructure, scores, adjacencyMatrices, "deletion");
			// Structures generated by reversal
			findBestNeighbor(ctbn, currentStructure, scores, adjacencyMatrices, "reversal");
			int idxBestOperation = Util.getIndexLargestValue(scores);
			double iterationBestScore = scores[idxBestOperation];
			logger.trace("Iteration best score {}", iterationBestScore);
			if (iterationBestScore > solution.getScore()) {
				logger.debug("Score improved! From {} to {}", solution.getScore(), iterationBestScore);
				logger.debug("New structure: {}", (Object) adjacencyMatrices[idxBestOperation]);
				currentStructure = adjacencyMatrices[idxBestOperation];
				solution.setAdjacencyMatrix(adjacencyMatrices[idxBestOperation]);
				solution.setScore(iterationBestScore);
				improvement = true;
			}
		} while (improvement);
		return solution;
	}

	@Override
	public HillClimbingSolution findStructure(PGM<? extends Node> pgm, int idxNode) {
		throw new NotImplementedException("Feature not yet implemented");
	}

	@Override
	public HillClimbingSolution findStructure(PGM<? extends Node> pgm, List<Integer> idxNodes) {
		throw new NotImplementedException("Feature not yet implemented");
	}

	@Override
	public String getIdentifier() {
		return "Hill climbing";
	}

	@Override
	public Map<String, String> getInfoScoreFunction() {
		return Map.of("scoreFunction", this.scoreFunction.getIdentifier(), "penalisationFunction",
				this.scoreFunction.getNamePenalisationFunction());
	}

	@Override
	public Map<String, String> getParametersAlgorithm() {
		return getInfoScoreFunction();
	}

	/**
	 * Checks if an arc between two nodes can be added. Arcs from any node to a class variable cannot be added, removed
	 * or reversed, and self-loops are also avoided.
	 *
	 * @param ctbn ctbn that contains the nodes
	 * @param i    index first node
	 * @param j    index second node
	 * @return true if the arc can be added, false otherwise
	 */
	private boolean checkModificationAdjacencyMatrix(CTBN<? extends Node> ctbn, int i, int j) {
		return i != j && !ctbn.getNodeByIndex(j).isClassVariable();
	}

	/**
	 * Computes the score of a structure given an adjacency matrix.
	 *
	 * @param adjacencyMatrix adjacency matrix
	 * @return score score of the structure
	 */
	private double computeScore(CTBN<? extends Node> ctbn, boolean[][] adjacencyMatrix) {
		// Set structure and obtain its score
		ctbn.setStructureModifiedNodes(adjacencyMatrix);
		return this.scoreFunction.compute(ctbn);
	}

	private void findBestNeighbor(CTBN<? extends Node> ctbn, boolean[][] bestStructure, double[] scores,
								  boolean[][][] adjacencyMatrices, String operation) {
		// Define the index of the operation. It will be used to store the score and
		// adjacency matrix
		// in the correct position of the arrays.
		int idxOperation = operation.equals("addition") ? 0 : operation.equals("deletion") ? 1 : 2;
		int numNodes = bestStructure.length;
		for (int i = 0; i < numNodes; i++) {
			for (int j = 0; j < numNodes; j++)
				if (checkModificationAdjacencyMatrix(ctbn, i, j)) {
					// Copy current best neighbour
					boolean[][] tempAdjacencyMatrix = new boolean[bestStructure.length][];
					for (int r = 0; r < bestStructure.length; r++)
						tempAdjacencyMatrix[r] = bestStructure[r].clone();
					if (operation.equals("addition")) {
						// An arc is added
						if (tempAdjacencyMatrix[i][j])
							// If there is already an arc, the operation is not performed
							continue;
						// Arc is added
						tempAdjacencyMatrix[i][j] = true;
					} else if (operation.equals("deletion")) {
						// An arc is removed
						if (!tempAdjacencyMatrix[i][j])
							// If there is no arc, the operation cannot be performed
							continue;
						// Arc is removed
						tempAdjacencyMatrix[i][j] = false;
					} else {
						// An arc is reversed
						if (!tempAdjacencyMatrix[i][j] || ctbn.getNodeByIndex(i).isClassVariable())
							// If there is no arc, the operation cannot be performed. An arc from a class to
							// a feature variable cannot be reversed
							continue;
						// Arc is reversed
						tempAdjacencyMatrix[i][j] = false;
						tempAdjacencyMatrix[j][i] = true;
					}
					if (ctbn.isStructureLegal(tempAdjacencyMatrix)) {
						logger.trace("Studying new {} structure: {}", ctbn.getType(), tempAdjacencyMatrix);
						// Retrieve score CTBN with the modified adjacency matrix
						double score = computeScore(ctbn, tempAdjacencyMatrix);
						if (scores[idxOperation] < score) {
							scores[idxOperation] = score;
							adjacencyMatrices[idxOperation] = tempAdjacencyMatrix;
						}
					}
				}
		}
	}

}